### ISSUE TITLE
Calling .end() after .pipe() closes the stream silently

### ISSUE THREAD

**Issue by diasdavid** [mafintosh/protocol-buffers-stream#1]
I noticed that if I call the `.end` after `.pipe`, having done a `stream.<messageType>` before, simple closes the stream and doesn't actually send the protobuf. I feel that I'm probably missing something, thoughts?

**Comment by mafintosh** [comment]
can you share a gist of what you are doing? in general you shouldn't call .end yourself unless in very specific use cases.

**Comment by diasdavid** [comment]
This is the simple example : http://gateway.ipfs.io/ipfs/QmXq7qa8AvsaJBfwfj6CQDV5RsLi6wXsZcpHbPSEBCpr18

But the idea is to be able to write the protobuf and halfClose a spdy stream:
https://github.com/diasdavid/node-ipfs-swarm/blob/master/src/identify/index.js#L54-L76

**Comment by mafintosh** [comment]
you shouldn't call end in your example. that will teardown the pipeline. pipe will call .end for you when its flushed.

call `stream.finalize()` (https://github.com/mafintosh/protocol-buffers-stream/blob/master/index.js#L86-L88) or `stream.push(null)` after writing your messages instead which signals that readable part of the stream is done :)

**Comment by diasdavid** [comment]
cool! didn't know of finalize() :) Thank you @mafintosh

**Comment by mafintosh** [comment]
i didn't document it which is probably why hehe
