### ISSUE TITLE
Pass an array of Buffers

### ISSUE THREAD

**Issue by diasdavid** [mafintosh/protocol-buffers-stream#2]
What would be the best way to pass an array of buffers, using the type 'bytes' in .proto?  (https://github.com/diasdavid/node-ipfs-swarm/blob/master/src/identify/identify.proto#L16)

I could create a new buffer from the concat of every buffer, but then I would be able to properly slice each buffer in the other end, right?

Another way could be converting each buffer to its string format, JSON.stringify the array, create a buffer from the string and then do the reverse in the other side, but this is probably not the best approach, is it??!

Thank you :)

**Comment by diasdavid** [comment]
Forget about it, I was doing something wrong, but now, **it works** :) Thank you anyways :)

**Comment by mafintosh** [comment]
Glad to be of service lol!

**Comment by jbenet** [comment]
http://gateway.ipfs.io/ipfs/QmVyg3HNYcAtxsrWcxomqzcJwhXSNGweXU1P12A2GBzCJS/itworks.mp3
