### ISSUE TITLE
Header not cleaned leads to crash

### ISSUE THREAD

**Issue by Alan01252** [mafintosh/protocol-buffers-stream#3]
Hi @mafintosh

Apologies in advance if this is nonsense, this has been a learning curve and a half! :)

I *think* there's a bug when you get a header with more than one MSB set as the _header is never cleared in the _onheader function.

What happens is if you get a varint in the header which spans multiple bytes the header bytes get correctly set, however the additional bytes aren't cleared before the next time _.onheader is called.

So if for instance you have a header like this come in

 <Buffer 8d 85 06 02 ...

The first 3 bytes of the header get set to

<Buffer 8d 85 06

and varint decode works as expected, but then if the next value comes in is

 <Buffer 20 00 0a 0d 

Because the header isn't cleared it now contains

<Buffer 20 85 06

and varint decode returns the wrong value and bad things happen

I did something dirty and added this._header.fill(0);  after this._missing and that seems to make everything behave as expected.

If you have time I'd greatly appreciate you having a look and making sure I'm not going mad.

Thank you.

Alan

**Comment by mafintosh** [comment]
varint only decodes the first varint in a buffer so this should be a problem. do you have a test case that reproduces the bug?

**Comment by Alan01252** [comment]
Sorry not yet.. I'll work on it :(

Varint decodes the first varint in the buffer, but the varint it decodes is wrong because the bytes in the header aren't correct, because they're not cleared in the case where the varint spans multiple bytes.

**Comment by mafintosh** [comment]
Hmm I cannot get varint to decode a int wrong (even if the buffer contains multiple MSBs). Do you have an example of a buffer with multiple MSBs where the varint decoded is wrong?

**Comment by Alan01252** [comment]
Sorry it's not that varint decoded returns the wrong value. It's the _.header buffer contains wrong data.

So the problem comes the second time   Messages.prototype._onheader = function (data) { } is called, when the first time it's called the data contains a varint with multiple MSBs.

So first time Messages.prototype._onheader = function (data) { }  is called with data === <Buffer 8d 85 06 02 ...

 this._header[this._ptr++] = data[i]
      if (data[i] & 0x80) continue

this._header contains <Buffer 8d 85 06  ...

Second time it's called with Data = <Buffer 20 00 0a 0d this._header still contains <Buffer 8d 85 06 ...
and so when you call varint.decode(this._header) you as it to decode <Buffer 20 85 06 rather than just <Buffer 20 00 00.

Sorry I'm not explaining myself very well and struggling with another little bug I'm trying to fix too :)

I'll get there

**Comment by mafintosh** [comment]
Hmm. I don't understand why that would be a problem. varint only returns the first one so `varint.decode(new Buffer([0x20, 0x85, 0x06]))` and `varint.decode(new Buffer([0x20, 0x00, 0x00]))` both return the same result (32)

**Comment by Alan01252** [comment]
Bah, I might have messed my example values up... but varint will look at every byte until it finds one without the MSB set so you can see if you don't clear the header how it will break things.

**Comment by Alan01252** [comment]
I get what you're saying now I think. I now think i've messed up and it's this later bug that's causing me the issues, not what I *thought* this was...

**Comment by Alan01252** [comment]
This issue can be closed, I'm a muppet... Sorry for the time wasting. 

I was sending two streams of data back into one protocol buffer stream and it *really* didn't like it. 

Annoying it worked up to a point, and then fell over because a separate stream of bytes would come into the protocol buffer stream midway through it trying to work out the next emit. This would make the bytes sent to the on header function go completely wrong.

**Comment by mafintosh** [comment]
ah ok. no worries. to support that usecase you could wrap in a [multiplexer](https://github.com/maxogden/multiplex)

**Comment by Alan01252** [comment]
Thank you :)

There's still a problem here I can't solve I'm losing the plot tbh, i think might be beyond my little head...

 separated it out by just creating two classes each with their own proto buffer, that would be nicer but it's still, crashing.

**Comment by mafintosh** [comment]
If you end up making a test case that crashes when using this module let me know and I'll help you fix it
